site_name: etosamoe mkdocs demo
site_url: https://etoosamoe.github.io/mkdocs-demo/
theme:
  name: material
site_author: Yuriy Semyenkov
copyright: Yuriy Semyenkov, etogeek, 2024
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences